### ISSUE TITLE
Testing Issues Page

### ISSUE THREAD

**Issue by AvaAvarai** [CWU-VKD-LAB/javaPC#1]
# This is a test of our issues page.

Issues encountered:
- We need to test issues.
- Issues are untested.

@AvaAvarai Do you know about this?

**Comment by AvaAvarai** [comment]
What does this look like?

**Comment by AvaAvarai** [comment]
Can I necro?

**Comment by AvaAvaraiTest** [comment]
Can this non-associated account also necro?
